staticSites:
  - name: e-comm-store-frontend
    branch: master

    buildCommand: npm ci && npm run build -- --configuration=production
    publishPath: dist/webapp/browser

    redirects:
      - source: /*
        destination: /index.html
        status: 200

    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
